name: 💡 Feature Request
description: Suggest an idea or enhancement for the US Stock CSV Downloader
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - jkabutaro

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make this project better.

  - type: textarea
    id: feature-description
    attributes:
      label: 💡 Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you have in mind...
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: 🎯 Problem This Feature Would Solve
      description: Describe the problem or use case this feature would address.
      placeholder: What problem would this feature solve? What use case would it enable?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: ✨ Proposed Solution
      description: Describe how you envision this feature working.
      placeholder: How should this feature work? What should the user experience be like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Are there other ways to solve this problem? What alternatives have you considered?

  - type: dropdown
    id: feature-category
    attributes:
      label: 📂 Feature Category
      description: What category does this feature fall into?
      options:
        - Data Download Enhancement
        - New Data Source
        - Performance Improvement
        - User Interface/Experience
        - Configuration Options
        - Error Handling
        - Output Format
        - Documentation
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority-level
    attributes:
      label: 🎯 Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical need
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🔧 Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change)
        - Moderate (some development needed)
        - Complex (significant development required)
        - I'm not sure

  - type: textarea
    id: example-usage
    attributes:
      label: 💻 Example Usage
      description: Show how this feature would be used (command line examples, configuration, etc.)
      placeholder: |
        # Example command or usage
        USStockDownloader --new-feature --option value
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information that would help understand this feature request...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature and its benefits
          required: true
        - label: I understand this is an open source project and feature implementation depends on maintainer availability
          required: true