name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: './USStockDownloader'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --logger trx --results-directory "TestResults"
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Test Results
        path: ${{ env.PROJECT_PATH }}/TestResults/*.trx
        reporter: dotnet-trx
        
    - name: Publish Application
      run: dotnet publish --configuration Release --output ./publish --self-contained false
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: USStockDownloader-${{ github.sha }}
        path: ${{ env.PROJECT_PATH }}/publish/
        retention-days: 7
